default: &default
  adapter: postgresql
  port: 5432
  username: postgres
  password: postgres
  host: localhost


development:
  <<: *default
  database: health_portal_development

test:
  <<: *default
  database: health_portal_test

# production:
#   <<: *default
#   database: health_portal_production
#   username: health_portal
#   password: <%= ENV["HEALTH_PORTAL_DATABASE_PASSWORD"] %>